import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const assetsRoot = resolve(root, 'src', 'assets')
const generatedRoot = resolve(root, 'src', 'client')

const assetFiles = {
  lightHero: 'angelina-light-hero.webp',
  darkHero: 'angelina-dark-hero.webp',
  lightThread: 'angelina-light-thread.webp',
  darkThread: 'angelina-dark-thread.webp',
  lightParallaxBackground: 'angelina-light-parallax-background.webp',
  lightParallaxForeground: 'angelina-light-parallax-foreground.webp',
}

const assets = {}
for (const [key, filename] of Object.entries(assetFiles)) {
  const bytes = await readFile(resolve(assetsRoot, filename))
  assets[key] = `data:image/webp;base64,${bytes.toString('base64')}`
}

const themes = JSON.parse(await readFile(resolve(root, 'src', 'themes.json'), 'utf8'))
const orderedThemes = ['angelina-light', 'angelina-dark'].map((id) => {
  const theme = themes[id]
  if (theme === undefined) throw new Error(`themes.json is missing ${id}`)
  return theme
})

const header = '// Generated by scripts/generate-assets.mjs. Do not edit by hand.\n'
await writeFile(
  resolve(generatedRoot, 'assets.generated.ts'),
  `${header}export const ANGELINA_ASSETS = Object.freeze(${JSON.stringify(assets)} as const)\n`,
  'utf8',
)
await writeFile(
  resolve(root, 'src', 'themes.generated.ts'),
  `${header}export const ANGELINA_THEMES = Object.freeze(${JSON.stringify(orderedThemes)} as const)\n`,
  'utf8',
)

console.log(`generated ${Object.keys(assets).length} image data URIs and ${orderedThemes.length} theme definitions`)
